version: "3.8"

services:
  db:
    image: postgres:10-alpine
    env_file: .env
    container_name: db

  api:
    build: ./

    # Run Django startup commands
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py collectstatic --noinput &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"

    env_file: .env

    volumes:
      - ./app:/api

    depends_on:
      - db 

    container_name: api

    # 🔒 SECURITY + RESOURCE RESTRICTIONS

    mem_limit: 512m        # Limit container memory to 512MB
    cpus: 1.0            # Limit to 1 CPU core
    read_only: true        # Make container filesystem read-only
    security_opt:
      - no-new-privileges:true  # Prevent privilege escalation
    cap_drop:
      - ALL               # Drop all Linux capabilities for minimal privilege



