name: Setup Env
description: Reusable setup steps for CI jobs

runs:
  using: "composite"
  steps:
    - name: Make Env file
      run: mv .sample.build.env .env
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version
      shell: bash
