name: Setup Env
description: Reusable setup steps for CI jobs

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make Env file
      run: mv .sample.build.env .env
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

