name: 'Setup Docker Environment'
description: 'Sets up Docker Buildx and cache for builds'
inputs:
  load-image:
    description: 'Whether to load the cached Docker image'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Make Env file
      run: mv .sample.build.env .env
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Install Docker Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.23.3

    - name: Load cached Docker image
      if: inputs.load-image == 'true'
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: app:latest
        cache-from: type=local,src=/tmp/.buildx-cache