name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [develop,main]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      ecr-repository: ${{ github.event.workflow_run.head_branch == 'main' && secrets.PROD_ECR_REPO || github.event.workflow_run.head_branch == 'develop' && secrets.STAGING_ECR_REPO }}
      environment: ${{ github.event.workflow_run.head_branch == 'main' && secrets.PROD_ENV || github.event.workflow_run.head_branch == 'develop' && secrets.STAGING_ENV }}
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
