name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [develop,main]
    types:
      - completed

permissions:
  contents: read
  packages: write  # Required for pushing Docker images

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker

      - name: Deploy to production
        run: echo "Deploying to production environment..."
        env:
          DEPLOY_ENV: production
