name: CI Container Pipeline

on:
  workflow_run:
    workflows: ["Continuous Integration Checks"]
    branches: [develop,main]
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
 
  deploy-production:
    name: Deploy Production
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/reusable-container-deployment.yml
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.PROD_ECR_REPO }}
      DEPLOY_ENV: ${{ secrets.PROD_ENV }}
  
  deploy-staging:
    name: Deploy Staging
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'develop'
    uses: ./.github/workflows/reusable-container-deployment.yml
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.STAGING_ECR_REPO }}
      DEPLOY_ENV: ${{ secrets.STAGING_ENV }}