name: Continuous Integration

on:
  push:
    branches:
      - develop
      - main
  pull_request: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - name: Run tests
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - name: Run linter
        run: make lint

  isort:
    name: Isort
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-env
      - name: Check isort
        run: make check-isort
