name: Continuous Integration

on:
  push:
    branches:
      - develop
      - main
  pull_request: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: ./.github/actions/setup-env
      - name: Test
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: ./.github/actions/setup-env
      - name: Lint
        run: make lint

  isort:
    name: Isort
    runs-on: ubuntu-24.04
    steps:
      - uses: ./.github/actions/setup-env
      - name: Isort
        run: make check-isort
