name: Continuous Integration

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  
  build:
    name: Build Docker Image
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Setup env
        uses: ./.github/actions/setup-env/action.yml

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
     
        with:
          context: .
          load: true
          tags: app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

  # test:
  #   name: Test
  #   needs: setup
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Setup env
  #       uses: ./.github/actions/setup-env/action.yml  
  #     - name: Run tests
  #       run: make test

  # lint:
  #   name: Lint
  #   needs: setup
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Setup env
  #       uses: ./.github/actions/setup-env/action.yml
  #     - name: Run linter
  #       run: make lint

  # isort:
  #   name: Isort
  #   needs: setup
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Setup env
  #       uses: ./.github/actions/setup-env/action.yml
  #     - name: Check isort
  #       run: make check-isort

  # hadolint:
  #   name: Run Hadolint
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Run Hadolint
  #       uses: hadolint/hadolint-action@v3.1.0
  #       with:
  #         dockerfile: Dockerfile
