---
name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Env file
        run: mv .sample.build.env .env
      - name: Test
        run: make test

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Env file
        run: mv .sample.build.env .env
      - name: Lint
        run: make lint
  
  isort:
    name: Isort
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Env file
        run: mv .sample.build.env .env
      - name: Isort
        run: make check-isort
