name: Reusable Deployment Workflow

on:
  workflow_call:
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: true
      AWS_REGION:
        required: true
      ECR_REPOSITORY:
        required: true
      DEPLOY_ENV:
        required: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Environment
        uses: ./.github/actions/setup-docker

      - name: Get AWS permissions
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
          
      - name: Deploy to ${{ secrets.DEPLOY_ENV }}
        run: echo "Deploying to ${{ secrets.DEPLOY_ENV }} environment..."
        env:
          DEPLOY_ENV: ${{ secrets.DEPLOY_ENV }} 