name: Setup CI Env

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4

      - name: Make Env file
        run: mv .sample.build.env .env
        shell: bash

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container  # ✅ REQUIRED for cache export

      - name: Cache Docker layers
        uses: actions/cache@v4  # Updated to v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-